---
- name: Set timezone
  community.general.timezone:
    name: '{{ timezone }}'
  tags:
    - system
    - timezone

# cloud image には locales が入っていないことがある
- name: Install locales package
  ansible.builtin.package:
    name: locales
    state: present
  tags:
    - system
    - locale

- name: Generate locales
  community.general.locale_gen:
    name: '{{ item }}'
    state: present
  loop: '{{ locales }}'
  tags:
    - system
    - locale

- name: Add users
  ansible.builtin.user:
    name: '{{ item.name }}'
    groups: '{{ item.groups }}'
    password: '{{ item.password }}'
    state: '{{ item.state }}'
    comment: '{{ item.comment }}'
    update_password: on_create
  loop: '{{ users }}'
  tags:
    - users

- name: Set authorized_keys
  ansible.posix.authorized_key:
    user: '{{ item.name }}'
    key: "{{ lookup('file', item.key) }}"
    state: present
    exclusive: true
  loop: '{{ users }}'
  when:
    - item.state == 'present'
  tags:
    - users
    - authorized_keys

- name: Set aliases
  ansible.builtin.blockinfile:
    path: '/home/{{ item.name }}/.bashrc'
    block: '{{ bashrc_block }}'
  loop: '{{ users }}'
  tags:
    - users
    - bashrc
