---
- name: Initdb PostgreSQL
  ansible.builtin.command: initdb
  become: true
  become_user: postgres
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
  tags:
    - postgres

- name: Restart PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: true
  tags:
    - postgres
