---
- name: Debug play
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Show product uuid
      ansible.builtin.debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

    - name: Show default gateway
      ansible.builtin.debug:
        msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: ansible_default_ipv4.gateway is defined

    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
